version: "3"

services:
  marcel_knowhhow_frontend:
    container_name: marcel_knowhhow_frontend
    image: jnicontainerregistry.azurecr.io/marcel_knowhhow_frontend
    ports:
      - 80:80
    restart: unless-stopped 
    deploy:
      resources:
        limits:
          memory: 500m