version: "3"

services:
  marcel_knowhow_frontend:
    container_name: marcel_knowhow_frontend
    image: marcel_knowhow_frontend
    ports:
      - 80:80
    restart: unless-stopped 
    deploy:
      resources:
        limits:
          memory: 500m